import Q9R5Stage127

/-!
  Final wrapper for the staged q=9, r=5 LRAT replay.

  The stage chain is generated by `certificates/q9/generate_lrat_stages_r5.py`
  and compiled separately from the default build because the trace is large.
-/

namespace Erdos811Q9NoInfR5CNF

theorem q9_noinf_r5_unsat_partitioned_staged :
    q9_noinf_r5_ctx.proof ([]) :=
  q9_r5_stage127

#print axioms q9_noinf_r5_unsat_partitioned_staged

end Erdos811Q9NoInfR5CNF
